/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helium314_keyboard_voice_whisper_WhisperGGML */

#ifndef _Included_helium314_keyboard_voice_whisper_WhisperGGML
#define _Included_helium314_keyboard_voice_whisper_WhisperGGML
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helium314_keyboard_voice_whisper_WhisperGGML
 * Method:    openNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_helium314_keyboard_voice_whisper_WhisperGGML_openNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     helium314_keyboard_voice_whisper_WhisperGGML
 * Method:    openFromBufferNative
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_helium314_keyboard_voice_whisper_WhisperGGML_openFromBufferNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     helium314_keyboard_voice_whisper_WhisperGGML
 * Method:    inferNative
 * Signature: (J[FLjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_helium314_keyboard_voice_whisper_WhisperGGML_inferNative
  (JNIEnv *, jobject, jlong, jfloatArray, jstring, jobjectArray, jobjectArray, jint, jboolean);

/*
 * Class:     helium314_keyboard_voice_whisper_WhisperGGML
 * Method:    cancelNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_helium314_keyboard_voice_whisper_WhisperGGML_cancelNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     helium314_keyboard_voice_whisper_WhisperGGML
 * Method:    closeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_helium314_keyboard_voice_whisper_WhisperGGML_closeNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif